fieldLayouts:
  2e5f2992-4ba7-46e4-9993-0f150ef3d2b7:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: 'ΓΑΚ Προσφυγής'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 4999e47a-f4c2-45d6-b94e-03d056c0ec73
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Αριθμός ΕΣΗΔΗΣ'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 50587a1a-0186-47b5-846b-25a56adb7446
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 506ff215-3474-4fe2-b532-ad32d49a3889
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0837909a-2b9b-4687-83f2-448137efd750
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 929f7814-368b-42b3-bbef-0be388e32c9a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 93aded48-0809-46f1-b29d-02e3c8320b74
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Στοιχεία Προσφυγής'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 33dcc34c-cdff-4b67-8b4c-2f0926546d4f
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cfba50f5-b2e4-4d36-a278-07a4e025b728
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Κατηγορία Προσφυγής'
        sortOrder: 4
handle: appeals
hasTitleField: true
name: Appeals
section: 7e75089c-dc8d-4420-a3d6-baedd9235a3f
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
