contentColumnType: string(800)
fieldGroup: 78fc08b7-81dd-47d8-873a-3600a2c65e38
handle: assigner
instructions: 'Παρακαλώ εισάγετε το όνομα της αναθέτουσας αρχής'
name: Assigner
searchable: false
settings:
  byteLimit: null
  charLimit: 200
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Εισαγωγή ονόματος αναθέτουσας αρχής'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
