contentColumnType: string(200)
fieldGroup: 78fc08b7-81dd-47d8-873a-3600a2c65e38
handle: judgement
instructions: 'Παρακαλώ εισάγετε τον αριθμό της απόφασης'
name: Judgement
searchable: false
settings:
  byteLimit: null
  charLimit: 50
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Εισαγωγή αριθμού απόφασης'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
